package com.example.pojo;/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/



public class _id {
	private java.lang.String $oid;

 	public void set$oid(java.lang.String $oid) {
		this.$oid = $oid;
	}

	public java.lang.String get$oid() {
		return $oid;
	}

}