/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.example.pojo;

public class Pojo {
	
	private int offset;
	
	
	private RowElement[] rows;

	private int total_rows;
	
	private Query query;
	
	private int millis;
	
 	public int getOffset() {
		return offset;
	}

	public void setOffset(int offset) {
		this.offset = offset;
	}

	public void setRows(RowElement[] rows) {
		this.rows = rows;
	}

	public RowElement[] getRows() {
		return rows;
	}

	public int getTotal_rows() {
		return total_rows;
	}

	public void setTotal_rows(int total_rows) {
		this.total_rows = total_rows;
	}

	

	public Query getQuery() {
		return query;
	}

	public void setQuery(Query query) {
		this.query = query;
	}

	public int getMillis() {
		return millis;
	}

	public void setMillis(int millis) {
		this.millis = millis;
	}

	
	
}