/* Generated by JavaFromJSON */
/*http://javafromjson.dashingrocket.com*/

package com.example.pojo;

public class RowElement 
{
	
	private _id _id;
	private java.lang.String password;

 	public void setPassword(java.lang.String password) {
		this.password = password;
	}

	public java.lang.String getPassword() {
		return password;
	}

	private java.lang.String username;

 	public void setUsername(java.lang.String username) {
		this.username = username;
	}

	public java.lang.String getUsername() {
		return username;
	}

	public _id get_id() {
		return _id;
	}

	public void set_id(_id _id) {
		this._id = _id;
	}

	
	
	

}